projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-2
        apiId: hsoocohnr5c2bmu6fo4l6dy4se
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
